/** ERROR CODES **/

var Code = {
  NOERROR: 0,
  ERROR_UNKNOWN_USER: 1,
  ERROR_INVALID_PWD: 2,
  ERROR_INVALID_SESSION: 3,
  ERROR_GENERAL: 4,
  ERROR_CPA_: 5,
  ERROR_CPA_NEW_ENGAGEMENT_MAIL: 6,
  ERROR_CREATE_ENGAGEMENT: 7,
  ERROR_CREATE_ENGAGEMENT_DIR: 8,
  ERROR_INSPECTOR: 9,
  ERROR_INSPECTOR_PERSON_DNE: 10,
  ERROR_CREATE_USER: 11,
  ERROR_CREATE_BUSINESS: 12,
  ERROR_CREATE_ACTIVITY: 13,

  core: {
    OK: 'core-000',
    ERROR: 'core-001',
    IO_NOT_SETUP: 'core-002',
    NO_SOCKET_CONNECTION: 'core-003',
    INACTIVE_USER: 'core-004',
    LOCKED_USER: 'core-005',
    ERROR_INSPECTOR: 'core-006',
    ERROR_GENERATE_AUTHID: 'core-007'
  },

  api: {
    OK: 'api-000',
    ERROR: 'api-001',
    UNSUPPORTED: 'api-002',
    MISSING_DATA_MODEL: 'api-003',
    MISSING_DEV_AUTHID: 'api-004',
    MISSING_DEV_APIKEY: 'api-005',
    MISSING_USER_AUTHID: 'api-006',
    MISSING_ACCESS_TOKEN: 'api-007',
    INVALID_ACCESS_TOKEN: 'api-008',
    EXPIRED_ACCESS_TOKEN: 'api-009',
    REGISTRATION_PENDING: 'api-010',
    REGISTRATION_REJECTED: 'api-011',
    REGISTRATION_APPROVED: 'api-012',
    REGISTRATION_ERROR: 'api-013',
    MISSING_IDQID: 'api-014',
    ACCESS_DENIED: 'api-015',
    MISSING_EMAIL: 'api-016',
    INVALID_EMAIL: 'api-017',
    MISSING_DEVICE_INFO: 'api-018',
    INVALID_DEVICE_INFO: 'api-019',
    MISSING_CONFIRMATION_CODE: 'api-020',
    INVALID_CONFIRMATION_CODE: 'api-021',
    DEVICE_ALREADY_REGISTERED: 'api-022',
    IDQ_PUSHMESSAGE_TOKEN: 'api-023'
  },

  db: {
    OK: 'db-000',
    ERROR: 'db-001',
    ERROR_OP_FIND: 'db-002',
    ERROR_OP_UPDATE: 'db-003',
    ERROR_OP_SAVE: 'db-004',
    DNE_USER: 'db-005',
    DNE_BUSINESS: 'db-006',
    DNE_ENGAGEMENT: 'db-007',
    DNE_MODEL: 'db-008',
    EXISTS_USER: 'db-009',
    DNE_DEVICE: 'db-010',
    DNE_IDQID: 'db-011'
  }
}

module.exports = Code
